"""Update feedback model

Revision ID: ec26fa9f513c
Revises: e25e7dd40f5a
Create Date: 2026-06-22 14:01:30.147024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec26fa9f513c'
down_revision: Union[str, None] = 'e25e7dd40f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('feedbacks', sa.Column('comment', sa.Text(), nullable=True))
    op.alter_column('feedbacks', 'rating',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='rating::integer')
    op.execute("UPDATE users SET role = 'STUDENT' WHERE role IS NULL")
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'ADMIN', 'MODERATOR', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'ADMIN', 'MODERATOR', name='userrole'),
               nullable=True)
    op.alter_column('feedbacks', 'rating',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('feedbacks', 'comment')
    op.drop_column('feedbacks', 'message')
    # ### end Alembic commands ###
